In [1]:
import numpy as np

### 1D Array In Numpy

In [3]:
x=np.array([1,2,3,4,5])
print(x,"\n",type(x))

[1 2 3 4 5] 
 <class 'numpy.ndarray'>


### 2D Array In Numpy

In [4]:
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x,"\n",type(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 
 <class 'numpy.ndarray'>


### MultiDymention Array in Numpy

In [8]:
x = np.array([[1,2,3,4,5],
              [1,2,3,4,5,6],
              [1,2,3,4,5,6,7],
              [1,2,3,4,5,6,7,8,9]], dtype=object)

print(x)
print("\nType:", type(x))
print("Shape:", x.shape)


[list([1, 2, 3, 4, 5]) list([1, 2, 3, 4, 5, 6])
 list([1, 2, 3, 4, 5, 6, 7]) list([1, 2, 3, 4, 5, 6, 7, 8, 9])]

Type: <class 'numpy.ndarray'>
Shape: (4,)


### All About Arrays


In [11]:
np.ones((3, 2))                          # Array of ones


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
np.zeros((2, 3))                         # Array of zeros


array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.full((4, 2, 4), 7)                       # Array of sevens


array([[[7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [13]:
np.eye(3)                                # Identity matrix



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.arange(0, 10, 2)                      # Range with step


array([0, 2, 4, 6, 8])

In [15]:
np.linspace(0, 1, 5)                     # 5 numbers from 0 to 1


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Vector

In [18]:
vector = np.array([10, 20, 30, 40])
print (vector)

[10 20 30 40]


### Matrix

In [21]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


### Tensor

In [23]:
tensor = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Operations

In [25]:
matrix.shape                                # Dimensions


(2, 3)

In [26]:
matrix.size                                 # Total elements



6

In [27]:
matrix.ndim                                 # Number of dimensions


2

In [28]:
matrix.dtype                                # Data type


dtype('int32')

In [29]:
matrix.reshape(2, 3)                        # Change shape

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
matrix.flatten()                            # 2D to 1D

array([1, 2, 3, 4, 5, 6])

In [31]:
v_col = matrix.reshape(-1, 1)
v_col.T  # Now it transposes correctly


array([[1, 2, 3, 4, 5, 6]])

###  Indexing, Slicing, Filtering



In [33]:
matrix[0], matrix[-1]                          # Indexing


(array([1, 2, 3]), array([4, 5, 6]))

In [34]:
matrix[1:4]                                 # Slicing


array([[4, 5, 6]])

In [35]:
matrix[matrix > 5]                             # Boolean filtering


array([6])

In [36]:
matrix[::2]                                 # Step slicing


array([[1, 2, 3]])

### Sorting

In [40]:
x=np.array([1,2,3,6,5,11,7,8])                   # for normal sorting
print(np.sort(x))

[ 1  2  3  5  6  7  8 11]


In [47]:
array_2d=np.array([[1,2],[3,4],[6,7]])
print(np.sort(array_2d,axis=0))                      # for row sorting
print(np.sort(array_2d,axis=1))                      # for column sorting


[[1 2]
 [3 4]
 [6 7]]
[[1 2]
 [3 4]
 [6 7]]


### Filter with Conditions

In [48]:
arr = np.array([10, 25, 30, 45, 60])
# Filter values > 30
filtered = arr[arr > 30]
print(filtered)

[45 60]


In [49]:
# Filter values between 20 and 50
filtered = arr[(arr > 20) & (arr < 50)]
print(filtered)

[25 30 45]


In [50]:
matrix = np.array([[10, 20], [30, 40], [50, 60]])

# Get rows where first column > 25
filtered_rows = matrix[matrix[:, 0] > 25]
print(filtered_rows)


[[30 40]
 [50 60]]


In [51]:
arr = np.array([5, 15, 25, 35])
indices = np.where(arr > 20)
print(indices)  # (array([2, 3]),)
print(arr[indices])


(array([2, 3], dtype=int64),)
[25 35]


In [52]:
arr = np.array([1, 2, 3, 4])
mask = np.array([True, False, True, False])
print(arr[mask])


[1 3]


### Aggregation Functions

In [54]:
arr = np.array([5, 15, 25, 35])

In [55]:
np.sum(arr), np.mean(arr), np.std(arr)


(80, 20.0, 11.180339887498949)

In [56]:
np.min(arr), np.max(arr), np.median(arr)



(5, 35, 20.0)

In [57]:
np.argmin(arr), np.argmax(arr)

(0, 3)

In [58]:

np.cumsum(arr), np.cumprod(arr)

(array([ 5, 20, 45, 80]), array([    5,    75,  1875, 65625]))

### Math Operations (Element-wise)



In [61]:
a = np.array([5, 15, 25, 35])
b = np.array([15, 5, 30, 45])

In [62]:
np.add(a, b), a + b                      # Addition


(array([20, 20, 55, 80]), array([20, 20, 55, 80]))

In [63]:
np.subtract(a, b), a - b                 # Subtraction



(array([-10,  10,  -5, -10]), array([-10,  10,  -5, -10]))

In [64]:
np.multiply(a, b), a * b                 # Multiplication


(array([  75,   75,  750, 1575]), array([  75,   75,  750, 1575]))

In [65]:
np.divide(a, b), a / b                   # Division

(array([0.33333333, 3.        , 0.83333333, 0.77777778]),
 array([0.33333333, 3.        , 0.83333333, 0.77777778]))

In [66]:

np.power(a, 2)                           # Exponentiation


array([  25,  225,  625, 1225], dtype=int32)

### Advanced Functions

In [74]:
arr = np.array([90, 35, 55, 85,85])

In [75]:
np.sort(arr)                             # Sorting


array([35, 55, 85, 85, 90])

In [76]:
np.unique(arr)                           # Unique values


array([35, 55, 85, 90])

In [79]:
a = np.array([5, 15, 25, 35])
b = np.array([15, 5, 30, 45])
np.concatenate([a, b], axis=0)           # Row-wise concat

array([ 5, 15, 25, 35, 15,  5, 30, 45])

In [80]:

np.vstack((a, b)), np.hstack((a, b))     # Stack arrays


(array([[ 5, 15, 25, 35],
        [15,  5, 30, 45]]),
 array([ 5, 15, 25, 35, 15,  5, 30, 45]))

### Linear Algebra (useful in advanced DA/ML)

In [93]:
a = np.array([5, 15, 25, 35])
b = np.array([15, 5, 30, 45])
matrix = np.array([[1, 2],[4,5]])

In [94]:
np.dot(a, b)                             # Dot product



2475

In [95]:
np.linalg.inv(matrix)                   # Inverse


array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [96]:
np.linalg.det(matrix)                   # Determinant


-2.9999999999999996

In [97]:
np.linalg.eig(matrix)                   # Eigenvalues

EigResult(eigenvalues=array([-0.46410162,  6.46410162]), eigenvectors=array([[-0.80689822, -0.34372377],
       [ 0.59069049, -0.9390708 ]]))